# -*- coding: utf-8 -*-
"""HotelQuiz.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kvczAqgzxBv5LAQmEHVWDYZe-lmlD6BE
"""

class huesped:
  def __init__(self, nombre, cedula, nhab):
    self.nhab = nhab
    self.nombre = nombre
    self.cedula = cedula

class habitacion:
  def __init__(self, numero):
    self.numero = numero
    self.disponible = True

  def ocupar(self):
    self.disponible = False

  def desocupar(self):
    self.disponible = True

class hotel:
    def __innnit__(self):
      self.habitaciones = 50

    def vacio(self):
      if self.cabeza == None:
        print("Está vacío el hotel")
      else:
        print("El hotel no está vacío")

    def entrada(self, cedula, nombre, nhab):
      if self.disponible == True:
        nuevo = huesped(cedula, nombre, nhab)
        self.huespedes[cedula] = nuevo
        llegadas = llegadas + 1
        self.habitaciones[nhab].ocupar()
        print("Huesped registrado")
      else:
        print("No está disponible")

    def salida(self, cedula):
      if self.disponible == False:
        habitacion = self.huespedes[cedula].nhab
        self.habitaciones[habitacion].desocupar()
        del self.huespedes[cedula]
      else:
        print("No está registrado")

    def cantidadHabitaciones(self):
      size = 0
      if(self.cabeza):
        habitacion_actual = self.cabeza
        while(habitacion_actual):
          size = size+1
          habitacion_actual = habitacion_actual.siguiente
          return size
      else:
        return 0